# Generated by Django 5.0.7 on 2026-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
