version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: swiftride_db
      POSTGRES_USER: swiftride_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               daphne -b 0.0.0.0 -p 8000 SwiftRide.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.example
    environment:
      - DATABASE_URL=postgres://swiftride_user:securepassword@db:5432/swiftride_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - USE_SQLITE=False
      - DEBUG=True
      - CELERY_TASK_ALWAYS_EAGER=False
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A SwiftRide worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env.example
    environment:
      - DATABASE_URL=postgres://swiftride_user:securepassword@db:5432/swiftride_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - USE_SQLITE=False
      - DEBUG=True
      - CELERY_TASK_ALWAYS_EAGER=False
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
