# Generated by Django 5.0.7 on 2024-08-08 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('class_type', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First Class')], max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('governorate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=50, unique=True)),
                ('train_type', models.CharField(choices=[('Express', 'Express'), ('Regional', 'Regional'), ('Freight', 'Freight')], max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('arrival_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriving_trains', to='tickets.station')),
                ('departure_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departing_trains', to='tickets.station')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('paid', 'paid'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('arrival_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_tickets', to='tickets.station')),
                ('departure_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_tickets', to='tickets.station')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.train')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tickets.train'),
        ),
        migrations.CreateModel(
            name='TrainStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.train')),
            ],
        ),
    ]
