# Generated by Django 5.0.7 on 2024-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trainstations',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trainstations',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
