# Generated by Django 5.0.7 on 2024-08-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_arrival_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
