# Generated by Django 5.0.7 on 2024-08-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_trips_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
