# Generated by Django 5.0.7 on 2024-08-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_trip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_available',
        ),
    ]
