# Generated by Django 5.0.7 on 2026-05-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_remove_seat_is_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatreservation',
            unique_together={('trip', 'seat', 'reservation_date')},
        ),
    ]
