# Generated by Django 5.0.7 on 2026-05-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_supplier'),
        ('tickets', '0011_alter_seatreservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trains', to='account.supplier'),
        ),
    ]
